language: R
cache: packages
dist: trusty
warnings_are_errors: true
r:
  - devel
  - oldrel
  - release

notifications:
  email:
    recipients:
      - pseudacris@gmail.com
    on_success: change
    on_failure: change
